import turtle
import math

turtle.setup(640, 480)
#my_turtle.bgcolor("LightGoldenrod1")
turtle.pensize(3)
turtle.speed(4)
turtle.pencolor("red")
turtle.penup()
turtle.goto(-100, 100)
turtle.pendown()
turtle.left(90)
turtle.pencolor("blue")
turtle.circle(40)
turtle.left(90)
turtle.penup()
turtle.back(5)
turtle.pendown()
turtle.pencolor("yellow")
turtle.circle(40)
turtle.penup()
turtle.back(85)
turtle.pendown()
turtle.right(90)
turtle.pencolor("black")
turtle.circle(40)

turtle.left(90)
turtle.penup()
turtle.back(5)
turtle.pendown()
turtle.pencolor("green")
turtle.circle(40)
turtle.penup()
turtle.back(85)
turtle.pendown()
turtle.right(90)
turtle.pencolor("red")
turtle.circle(40)
turtle.bgcolor('blue')
#my_turtle.left()
turtle.done()